### ISSUE TITLE
withdraw() not complete

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-piyaspark#15]
According to lab sheet

Withdraw the amount, using only items that have the
same currency as the parameter (amount).
amount must not be null and amount.getValue() > 0.

Don't forget to check for the conditions

**Comment by piyaspark** [comment]
If it still incorrect. Sorry for my mistake.

**Comment by bokherus** [comment]
You just need to check if amount is null or value of amount is less than 0.
